export type NumberDetailSource = 'pythagorean' | 'chaldean' | 'mulank' | 'bhagyank';

export interface NumberDetail {
  number: number;
  title: string;
  rulingPlanet: string;
  good: string;
  bad: string;
  famousPersonalities: string;
  // DOCX-based extended report fields (Basic 9 Planet Attributes)
  coreKarakTatva?: string[];
  lifeImpactArea?: string[];
  favourableColours?: string[];
  avoidColours?: string[];
  favourableDays?: string[];
  dayUse?: string[];
  primaryCrystalOrGemstone?: string[];
  alternativeCrystals?: string[];
  benefits?: string[];
  moneyFlow?: string[];
  workStyle?: string[];
  commonProblems?: string[];
  behavioralRemedy?: string[];
  description: string[];
}

export const NUMBER_DETAILS: Record<number, NumberDetail> = {
  1: {
    number: 1,
    title: 'The Originator',
    rulingPlanet: 'Sun',
    good: 'सम्मान, नेतृत्व, सफलता',
    bad: 'आत्मविश्वास कमी, authority conflict, identity crisis',
    famousPersonalities:
      'Captain Cook, Alexander – The Great, Hulk Hogan, Annie Besant, Tom Hanks',
    coreKarakTatva: [
      'Leadership (नेतृत्व शक्ति)',
      'Authority (अधिकार)',
      'Identity (आत्मपहिचान)',
      'Self-respect (आत्मसम्मान)',
      'Confidence (आत्मविश्वास)',
      'Government / Power (शासन शक्ति)',
      'Father / Authority figure',
    ],
    lifeImpactArea: ['Career direction', 'Social status', 'Recognition', 'Decision power', 'Public image'],
    favourableColours: ['Orange', 'Light Red', 'Copper tone'],
    avoidColours: ['Dark blue', 'Black (excess use)'],
    favourableDays: ['Sunday', 'Monday', 'Tuesday', 'Thursday'],
    dayUse: ['Important decision', 'New beginning', 'Meeting with authority', 'Business launch'],
    primaryCrystalOrGemstone: ['Ruby (Manik) (Don’t Use Without Analysis)'],
    alternativeCrystals: ['Sunstone', 'Red Carnel'],
    benefits: ['Confidence increase', 'Leadership activation', 'Authority respect', 'Career growth'],
    moneyFlow: ['Leadership role बाट', 'Position-based income', 'Authority-based earning'],
    workStyle: ['Independent', 'Decision maker', 'Control चाहिन्छ'],
    commonProblems: [
      'Career confusion',
      'Lack of confidence',
      'Recognition नपाउने',
      'Ego issue',
      'Father conflict',
    ],
    behavioralRemedy: ['Leadership role लिनु', 'Decision practice गर्नु', 'Self-respect maintain गर्नु'],
    description: [
      'Good planner with independent views.',
      'Inborn qualities of administration and leadership.',
      'Serious nature with firm thinking.',
      'Respected in social circles.',
      'More influenced by the Sun if born between July 21 and August 21.',
      'Attractive personality and progressing in life.',
      'Brilliant and not accepting defeat easily.',
      'Suitable for business in Jewellery, Gold, medical, medicines, army, scientific equipment, fire extinguishers, paper, cloth, and grains.',
      'Difficulty remaining under someone in administrative services; prefers roles like CEO or head of department.',
      "Warning: Avoid business of IRON despite success in other fields under the Sun's influence.",
      'Suggested directions for business, house, and employment: West, North-East, and North-West.',
    ],
  },
  2: {
    number: 2,
    title: 'The Peacemaker',
    rulingPlanet: 'Moon',
    good: 'emotional intelligence, connection power',
    bad: 'mood swing, confusion, emotional instability',
    famousPersonalities: 'Barack Obama, Jennifer Aniston, Johnny Depp',
    coreKarakTatva: [
      'Mind (मन / सोच्ने तरिका)',
      'Emotion (भावना)',
      'Sensitivity (संवेदनशीलता)',
      'Imagination (कल्पना शक्ति)',
      'Adaptability (अनुकूलन क्षमता)',
      'Mother (आमा)',
      'Mental peace (मानसिक शान्ति)',
    ],
    lifeImpactArea: [
      'Emotional stability',
      'Relationship bonding',
      'Decision making (emotion based)',
      'Mental health',
      'Public dealing',
    ],
    favourableColours: ['White', 'Cream', 'Silver tone'],
    avoidColours: ['Dark Red', 'Black (excess use)'],
    favourableDays: ['Monday', 'Sunday', 'Thursday'],
    dayUse: ['Relationship discussion', 'Emotional decisions', 'Family planning', 'Inner reflection'],
    primaryCrystalOrGemstone: ['Pearl (Moti) (Don’t Use Without Analysis)'],
    alternativeCrystals: ['Moonstone', 'Selenite'],
    benefits: ['Emotional stability', 'Mental peace', 'Relationship harmony', 'Decision clarity'],
    moneyFlow: ['People-based income', 'Service, hospitality, counselling', 'Public dealing'],
    workStyle: ['Supportive role', 'Team environment', 'Emotional comfort needed'],
    commonProblems: [
      'Mood swing',
      'Overthinking',
      'Decision confusion',
      'Relationship instability',
      'Emotional dependency',
    ],
    behavioralRemedy: ['Emotional control practice', 'Decision logic develop', 'Stable routine बनाउनु'],
    description: [
      'Natural diplomats with strong intuition.',
      'Cooperative and work well in partnerships.',
      'Creative and artistic inclinations.',
      'Emotionally sensitive; need emotional security.',
      'Suitable for fields like hospitality, nursing, arts, and water-related businesses.',
      'Favourable directions: North-West and West.',
    ],
  },
  3: {
    number: 3,
    title: 'The Communicator',
    rulingPlanet: 'Jupiter',
    good: 'growth, respect, wisdom',
    bad: 'wrong guidance, poor decisions, lack of growth',
    famousPersonalities: 'Albert Einstein, Steven Spielberg, Madonna',
    coreKarakTatva: [
      'Wisdom (बुद्धि / ज्ञान)',
      'Knowledge (शिक्षा)',
      'Expansion (विकास / विस्तार)',
      'Guidance (मार्गदर्शन)',
      'Ethics (नैतिकता)',
      'Spirituality (आध्यात्मिकता)',
      'Guru / Teacher energy',
    ],
    lifeImpactArea: [
      'Education & learning',
      'Career growth direction',
      'Financial expansion',
      'Marriage stability (especially for women)',
      'Decision based on values',
    ],
    favourableColours: ['Yellow', 'Golden Yellow', 'Mustard'],
    avoidColours: ['Dark Black', 'Excess Dark Blue'],
    favourableDays: ['Thursday', 'Sunday', 'Monday', 'Wednesday'],
    dayUse: ['Learning / teaching', 'Financial planning', 'Marriage-related decisions', 'Spiritual practices'],
    primaryCrystalOrGemstone: ['Yellow Sapphire (Pukhraj) (Don’t Use Without Analysis)'],
    alternativeCrystals: ['Citrine', 'Yellow Topaz'],
    benefits: ['Wisdom increase', 'Financial growth', 'Stability in decisions', 'Guru blessings'],
    moneyFlow: ['Teaching, consulting', 'Advisory roles', 'Knowledge-based income', 'Institutional work'],
    workStyle: ['Respect चाहिन्छ', 'Knowledge sharing role', 'Ethical working'],
    commonProblems: [
      'Wrong decisions',
      'गलत गुरु वा guidance',
      'Financial instability',
      'Overconfidence without knowledge',
      'Marriage instability',
    ],
    behavioralRemedy: ['सही गुरु / mentor खोज्नु', 'continuous learning', 'ethical decision practice'],
    description: [
      'Wise and optimistic; natural teachers and advisors.',
      'Generous and religious or philosophical leanings.',
      'Success in education, law, banking, and consultancy.',
      'Favourable directions: North-East, North, and East.',
    ],
  },
  4: {
    number: 4,
    title: 'The Builder',
    rulingPlanet: 'Rahu',
    good: 'massive growth, innovation, breakthrough',
    bad: 'confusion, illusion, गलत decision, sudden loss',
    famousPersonalities: 'Bill Gates, Oprah Winfrey, Arnold Schwarzenegger',
    coreKarakTatva: [
      'Innovation (नवीन सोच)',
      'Unconventional path (परम्परा बाहिरको बाटो)',
      'Illusion / Maya (भ्रम / आकर्षण)',
      'Ambition (अत्यधिक चाहना)',
      'Sudden rise & fall',
      'Foreign connection',
      'Technology / digital influence',
    ],
    lifeImpactArea: [
      'Business risk & innovation',
      'Sudden opportunities',
      'विदेश सम्बन्ध',
      'Social media / digital growth',
      'Unpredictable events',
    ],
    favourableColours: ['Smoky grey', 'Electric blue', 'Dark green', 'Metallic shades'],
    avoidColours: ['Too much black', 'Dull brown'],
    favourableDays: ['Saturday', 'Wednesday'],
    dayUse: ['Business experiment', 'Technology launch', 'New risk-based decision'],
    primaryCrystalOrGemstone: ['Hessonite (Gomed)'],
    alternativeCrystals: ['Smoky Quartz', 'Labradorite'],
    benefits: ['Confusion हटाउँछ', 'Decision clarity', 'Sudden loss protection', 'Focus improvement'],
    moneyFlow: [
      'Technology / IT',
      'Digital marketing',
      'Social media',
      'Foreign business',
      'Crypto / unconventional fields',
    ],
    workStyle: ['Non-traditional', 'Risk-taking', 'Experiment-driven', 'Fast-changing'],
    commonProblems: [
      'Overthinking',
      'भ्रम / गलत judgment',
      'Addiction tendency',
      'sudden loss',
      'unstable career',
      'गलत shortcut decision',
    ],
    behavioralRemedy: ['Risk before calculation', 'Mentorship लिनु', 'Shortcuts avoid गर्नु', 'Discipline develop गर्नु'],
    description: [
      'Practical and disciplined; strong work ethic.',
      'Good at building systems and structures.',
      'Success in real estate, construction, technology, and unconventional fields.',
      'Favourable directions: South-West and South.',
    ],
  },
  5: {
    number: 5,
    title: 'The Free Spirit',
    rulingPlanet: 'Mercury',
    good: 'smart earning, communication success, fast growth',
    bad: 'confusion, गलत decision, financial instability',
    famousPersonalities: 'Angelina Jolie, David Beckham, Mark Zuckerberg',
    coreKarakTatva: [
      'Communication (संचार शक्ति)',
      'Intelligence (बुद्धिमत्ता / analytical mind)',
      'Business skill (व्यापारिक क्षमता)',
      'Logic & calculation',
      'Adaptability (अनुकूलन क्षमता)',
      'Networking',
      'Youthful energy / quick thinking',
    ],
    lifeImpactArea: [
      'Business & trade',
      'Communication skill',
      'Money flow',
      'Learning speed',
      'Social interaction',
      'Decision making speed',
    ],
    favourableColours: ['Green', 'Light green', 'Emerald tone'],
    avoidColours: ['Dark red', 'Heavy black'],
    favourableDays: ['Wednesday', 'Sunday', 'Monday', 'Thursday', 'Friday'],
    dayUse: ['Business deals', 'Communication', 'Negotiation', 'Study / learning'],
    primaryCrystalOrGemstone: ['Emerald (Panna)'],
    alternativeCrystals: ['Green Aventurine', 'Peridot'],
    benefits: ['Communication clarity', 'Business growth', 'बुद्धि तेज बनाउँछ', 'Decision accuracy'],
    moneyFlow: ['Business', 'Trading', 'Sales', 'Marketing', 'Communication-based income'],
    workStyle: ['Fast-paced', 'Dynamic', 'Multi-tasking', 'Networking'],
    commonProblems: [
      'Confusion',
      'Decision error',
      'Overthinking',
      'Communication gap',
      'Financial instability',
      'Scattered focus',
    ],
    behavioralRemedy: ['Focus develop गर्नु', 'Decision slow गरेर लिनु', 'Skill polishing', 'Communication clarity'],
    description: [
      'Quick-witted and adaptable; excellent communicators.',
      'Success in trade, media, writing, and communication-related fields.',
      'Favourable directions: North and North-East.',
    ],
  },
  6: {
    number: 6,
    title: 'The Nurturer',
    rulingPlanet: 'Venus',
    good: 'attraction, luxury, happy relationship',
    bad: 'relationship issues, low self-worth, comfort loss',
    famousPersonalities: 'John Lennon, Michael Jackson, Marilyn Monroe',
    coreKarakTatva: [
      'Love (प्रेम)',
      'Relationship (सम्बन्ध)',
      'Luxury (सुविधा / भोग विलास)',
      'Beauty & aesthetics',
      'Attraction power',
      'Comfort & enjoyment',
      'Art & creativity',
    ],
    lifeImpactArea: [
      'Marriage & relationship',
      'Lifestyle quality',
      'Financial comfort',
      'Brand value',
      'Social attraction',
      'Creative expression',
    ],
    favourableColours: ['White', 'Light pink', 'Pastel shades'],
    avoidColours: ['Dirty / dull colour', 'Too much dark tone'],
    favourableDays: ['Friday', 'Wednesday', 'Saturday', 'Sunday'],
    dayUse: ['Relationship discussion', 'Financial comfort decision', 'Beauty / branding related work', 'Social interaction'],
    primaryCrystalOrGemstone: ['Diamond (Heera)'],
    alternativeCrystals: ['White Zircon', 'Opal'],
    benefits: ['Attraction power increase', 'Relationship harmony', 'Financial comfort', 'Creative energy activation'],
    moneyFlow: [
      'Fashion / beauty',
      'Luxury goods',
      'Art / entertainment',
      'Branding / design',
      'Relationship-based business',
    ],
    workStyle: [
      'Creative',
      'Presentation focused',
      'Relationship-driven',
      'Comfortable environment चाहिन्छ',
      '👉 Rough environment मा performance घट्छ',
    ],
    commonProblems: [
      'Relationship conflict',
      'Breakup / emotional dissatisfaction',
      'Financial comfort issues',
      'Over-dependency',
      'Lack of self-worth',
      'Indulgence (excess pleasure)',
    ],
    behavioralRemedy: [
      'Self-value develop गर्नु',
      'Healthy relationship boundaries',
      'खर्च control गर्नु',
      'Creative skill use गर्नु',
    ],
    description: [
      'Artistic and love beauty and harmony.',
      'Success in arts, fashion, entertainment, and luxury-related businesses.',
      'Favourable directions: South-East and South.',
    ],
  },
  7: {
    number: 7,
    title: 'The Seeker',
    rulingPlanet: 'Ketu',
    good: 'deep understanding, intuition, mastery',
    bad: 'confusion, isolation, directionless thinking',
    famousPersonalities: 'Johnny Depp, Leonardo DiCaprio, Michael Douglas',
    coreKarakTatva: [
      'Spirituality (आध्यात्मिकता)',
      'Detachment (वैराग्य)',
      'Research & analysis',
      'Intuition (अन्तर्ज्ञान)',
      'Isolation tendency',
      'Hidden knowledge',
      'Past life karmic influence',
    ],
    lifeImpactArea: [
      'Inner growth',
      'Research & deep study',
      'Spiritual journey',
      'अचानक detachment (relationship, job)',
      'confusion vs clarity phases',
    ],
    favourableColours: ['Smoky grey', 'Off white', 'Light brown'],
    avoidColours: ['Too bright flashy colours', 'Excess red'],
    favourableDays: ['Saturday', 'Thursday', 'Wednesday'],
    dayUse: ['Meditation', 'Deep study', 'Self-reflection', 'Research work'],
    primaryCrystalOrGemstone: ['Cat’s Eye (Lehsunia)'],
    alternativeCrystals: ['Labradorite', 'Amethyst'],
    benefits: ['Intuition increase', 'Confusion हटाउँछ', 'Spiritual clarity', 'Protection from illusion'],
    moneyFlow: [
      'Research-based work',
      'Occult science',
      'Healing / counselling',
      'IT backend / analytics',
      'Specialized niche skills',
    ],
    workStyle: [
      'Independent',
      'Deep focus',
      'Silent worker',
      'Less social interaction',
      '👉 Crowd-based काम मन पर्दैन',
    ],
    commonProblems: [
      'Confusion',
      'Overthinking',
      'Isolation',
      'Lack of direction',
      'Sudden detachment',
      'Spiritual escapism',
    ],
    behavioralRemedy: ['Practical action लिनु', 'Social connection maintain गर्नु', 'Overthinking control गर्नु', 'Reality check गर्नु'],
    description: [
      'Spiritual and analytical; drawn to mystery and research.',
      'Success in research, spirituality, healing, and unconventional paths.',
      'Favourable directions: North-East and North-West.',
    ],
  },
  8: {
    number: 8,
    title: 'The Achiever',
    rulingPlanet: 'Saturn',
    good: 'stability, long-term success, authority',
    bad: 'delay, struggle, frustration, financial issues',
    famousPersonalities: 'Pablo Picasso, Neil Armstrong, Paul McCartney',
    coreKarakTatva: [
      'Karma (कर्म फल)',
      'Discipline (अनुशासन)',
      'Hard work (परिश्रम)',
      'Delay & patience',
      'Justice (न्याय)',
      'Responsibility',
      'Structure & system',
    ],
    lifeImpactArea: [
      'Career stability',
      'Financial discipline',
      'Long-term wealth',
      'Life challenges',
      'Responsibility handling',
      'Slow but strong success',
    ],
    favourableColours: ['Dark blue', 'Navy blue', 'Black (controlled use)', 'Indigo'],
    avoidColours: ['Too bright colours', 'Excess Red & Orange'],
    favourableDays: ['Saturday', 'Friday', 'Wednesday'],
    dayUse: ['Long-term planning', 'Work discipline', 'Financial structure', 'Karma correction activities'],
    primaryCrystalOrGemstone: ['Blue Sapphire (Neelam) (only after proper consultation)'],
    alternativeCrystals: ['Amethyst', 'Black Tourmaline'],
    benefits: ['Stability', 'Focus', 'Protection', 'Discipline increase'],
    moneyFlow: ['Hard work', 'Industry / labor', 'Real estate', 'Long-term investment', 'System-based business'],
    workStyle: ['Structured', 'Routine-based', 'Disciplined', 'Long hours work'],
    commonProblems: [
      'Delay',
      'Depression',
      'Financial blockage',
      'Hard work without result',
      'Isolation',
      'Fear of failure',
    ],
    behavioralRemedy: ['Patience develop गर्नु', 'Routine follow गर्नु', 'Long-term सोच्नु', 'Responsibility लिनु'],
    description: [
      'Ambitious with strong sense of responsibility.',
      'Success in administration, mining, labour, and long-term ventures.',
      'Favourable directions: West and South-West.',
    ],
  },
  9: {
    number: 9,
    title: 'The Humanitarian',
    rulingPlanet: 'Mars',
    good: 'victory, action, bold success',
    bad: 'anger issues, conflict, गलत decision, loss',
    famousPersonalities: 'Mahatma Gandhi, Jim Carrey, Harrison Ford',
    coreKarakTatva: [
      'Courage (साहस)',
      'Action (कार्य गर्ने शक्ति)',
      'Energy (शारीरिक र मानसिक ऊर्जा)',
      'Aggression (आक्रामकता)',
      'Competition (प्रतिस्पर्धा)',
      'Protection / Defense',
      'Leadership in battlefield situations',
    ],
    lifeImpactArea: [
      'Decision execution',
      'Competition & success',
      'Conflict handling',
      'Physical energy',
      'Risk-taking ability',
      'Protection instinct',
    ],
    favourableColours: ['Red', 'Dark red', 'Maroon', 'Coral shades', 'Orange'],
    avoidColours: ['Excess white', 'Too soft pastel shades'],
    favourableDays: ['Tuesday', 'Sunday', 'Thursday', 'Friday'],
    dayUse: ['Action taking', 'Competitive tasks', 'Risk decisions', 'Physical work'],
    primaryCrystalOrGemstone: ['Red Coral (Moonga)'],
    alternativeCrystals: ['Carnelian', 'Red Jasper'],
    benefits: ['Energy increase', 'Courage boost', 'Decision power', 'Protection'],
    moneyFlow: [
      'Defense / Army',
      'Police / security',
      'Sports',
      'Engineering',
      'Surgery',
      'Competitive business',
    ],
    workStyle: ['Fast action', 'Risk-taking', 'Competitive', 'Result-oriented'],
    commonProblems: [
      'Anger',
      'Conflict',
      'Impulsive decision',
      'Accidents',
      'Relationship fights',
      'Loss due to aggression',
    ],
    behavioralRemedy: [
      'Anger control',
      'Decision pause practice',
      'Energy सही direction मा लगाउनु',
      'Discipline maintain गर्नु',
    ],
    description: [
      'Courageous and energetic; natural leaders.',
      'Success in army, sports, surgery, real estate, and fire-related industries.',
      'Favourable directions: South, South-East, and North-East.',
    ],
  },
};

export function getNumberDetail(n: number): NumberDetail | null {
  // Always reduce to a 1–9 digit so any valid numerology result
  // (Mulank, Bhagyank, name numbers, or their sums) maps to a report.
  if (!Number.isFinite(n)) return null;
  const abs = Math.abs(Math.trunc(n));
  if (abs === 0) return null;
  const single = ((abs - 1) % 9) + 1; // 1..9 cycle
  return NUMBER_DETAILS[single] ?? null;
}

